name: multiformer

channels:
- pytorch
- conda-forge
- defaults

dependencies:
- python=3.8
- pip=21.3.1
- ipykernel=6.4.1
- pytorch=1.8
- torchaudio=0.8
- torchvision=0.9
- cudatoolkit=10.2
- wandb=0.12.1
- editdistance=0.6.0

- pip:
    - local-attention==1.4.3
    - performer-pytorch==1.1.3
    - sentencepiece==0.1.96
    - sacrebleu==1.4.12
    - pandas==1.3.4
    - seaborn==0.11.2
    - tabulate==0.8.9